apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c" , "while true; do date >> /data/message.txt; sleep 5; done"]
      volumeMounts:
        - name: data-volume
          mountPath: /data
  volumes:
    - name: data-volume
      emptyDir: {}
