kind: Pod
apiVersion: v1
metadata:
  name: mysql-secrets-pod
spec:
  containers:
    - name: mysql-container
      image: mysql:8.0

      envFrom:
        - secretRef:
            name: db-credentials
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER  
      volumeMounts:
        - name: mysql-secrets-volume
          mountPath: /etc/db-credentials
          readOnly: true
  volumes:
    - name: mysql-secrets-volume
      secret:
        secretName: db-credentials
